# s-style Python 3.11 test service
service: test-service
runtime: python311

instance_class: F1
automatic_scaling:
  max_instances: 2

entrypoint: gunicorn -b :$PORT main:app

handlers:
# 静的ファイル - CSS, JS, 画像など
- url: /test/css
  static_dir: static_dir/css

- url: /test/js
  static_dir: static_dir/js

- url: /test/cmn_img
  static_dir: static_dir/cmn_img

- url: /test/top_img
  static_dir: static_dir/top_img

- url: /test/static
  static_dir: static_dir

- url: /test/favicon\.ico
  static_files: static_dir/favicon.ico
  upload: static_dir/favicon\.ico

# 動的ルート
- url: /test/.*
  script: auto
  secure: always

env_variables:
  GCP_PROJECT: 's-style-hrd'
